server:
  port: 8081

spring:
  application:
    name: ticketing
  kafka:
    bootstrap-servers: kafka-service:9092
    # producer:
      # key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # retries: 0
      # batch-size: 16384
    consumer:
      group-id: ticketing-group
      # auto-offset-reset: earliest  # What to do when no initial offset is found
      # key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # properties:
      #   spring.json.trusted.packages: com.ticketing.ticketing.kafka
  data:
    redis:
      host: redis-service
      port: 6379
      password: ""

app:
  jwt:
    issuer: "no24-api-server"
    audience: "no24-tkt-server"
    expiration-seconds: 3600
  kafka:
    payment-topic: ticketing.payment.requested
    payment-concurrency: 5   # Kafka 파티션 수와 반드시 일치시킬 것
# logging:
#   level:
#     org.springframework.kafka: DEBUG
#     org.apache.kafka.clients.consumer: DEBUG
